export const fallbackDashboard = {
  occupancyRate: 78,
  monthlyRevenue: 84250,
  activeReservations: 18,
  maintenanceOpen: 3,
  todayCheckins: 5,
  todayCheckouts: 4,
  recentReservations: [
    {
      id: 1001,
      cliente: "Mariana Costa",
      chale: "Chale das Araucarias",
      checkin: "2026-04-05",
      checkout: "2026-04-08",
      status: "confirmada",
      origem: "site",
      valorTotal: 1950
    },
    {
      id: 1002,
      cliente: "Carlos Mendes",
      chale: "Chale Vista do Vale",
      checkin: "2026-04-06",
      checkout: "2026-04-09",
      status: "pendente",
      origem: "whatsapp",
      valorTotal: 1480
    },
    {
      id: 1003,
      cliente: "Fernanda Rocha",
      chale: "Cabana da Serra",
      checkin: "2026-04-07",
      checkout: "2026-04-10",
      status: "hospedado",
      origem: "booking",
      valorTotal: 2240
    }
  ]
};

export const fallbackChales = [
  {
    id: 1,
    codigo: "CH-001",
    nome: "Chale das Araucarias",
    descricao: "Unidade premium para casais e familias pequenas.",
    capacidadeMaxima: 4,
    qtdQuartos: 2,
    qtdBanheiros: 1,
    qtdCamasCasal: 1,
    qtdCamasSolteiro: 2,
    localizacaoInterna: "Alameda Norte",
    status: "ativo",
    valorDiariaBase: 650,
    areaM2: 45,
    checkinPadrao: "14:00",
    checkoutPadrao: "12:00"
  },
  {
    id: 2,
    codigo: "CH-002",
    nome: "Cabana da Serra",
    descricao: "Cabana ampla com vista principal do empreendimento.",
    capacidadeMaxima: 6,
    qtdQuartos: 3,
    qtdBanheiros: 2,
    qtdCamasCasal: 2,
    qtdCamasSolteiro: 2,
    localizacaoInterna: "Mirante Central",
    status: "manutencao",
    valorDiariaBase: 740,
    areaM2: 68,
    checkinPadrao: "14:00",
    checkoutPadrao: "12:00"
  },
  {
    id: 3,
    codigo: "CH-003",
    nome: "Chale Vista do Vale",
    descricao: "Unidade compacta para hospedagens romanticas.",
    capacidadeMaxima: 2,
    qtdQuartos: 1,
    qtdBanheiros: 1,
    qtdCamasCasal: 1,
    qtdCamasSolteiro: 0,
    localizacaoInterna: "Bosque Sul",
    status: "ativo",
    valorDiariaBase: 520,
    areaM2: 32,
    checkinPadrao: "14:00",
    checkoutPadrao: "12:00"
  }
];

export const fallbackClientes = [
  {
    id: 1,
    nomeCompleto: "Mariana Costa",
    cpf: "12345678901",
    rg: "2001002001",
    documentoEstrangeiro: "",
    dataNascimento: "1991-04-12",
    telefone: "(85) 3333-1001",
    cidade: "Fortaleza",
    email: "mariana@example.com",
    celular: "(85) 99999-1001",
    logradouro: "Rua das Flores",
    numero: "128",
    complemento: "Apto 302",
    bairro: "Aldeota",
    estado: "CE",
    cep: "60150-160",
    pais: "Brasil",
    status: "recorrente",
    observacao: "Cliente recorrente de fim de semana."
  },
  {
    id: 2,
    nomeCompleto: "Carlos Mendes",
    cpf: "23456789012",
    rg: "3002003002",
    documentoEstrangeiro: "",
    dataNascimento: "1987-09-21",
    telefone: "(81) 3222-2002",
    cidade: "Recife",
    email: "carlos@example.com",
    celular: "(85) 99999-2002",
    logradouro: "Av. Boa Viagem",
    numero: "4500",
    complemento: "",
    bairro: "Boa Viagem",
    estado: "PE",
    cep: "51021-000",
    pais: "Brasil",
    status: "corporativo",
    observacao: ""
  },
  {
    id: 3,
    nomeCompleto: "Fernanda Rocha",
    cpf: "34567890123",
    rg: "4003004003",
    documentoEstrangeiro: "",
    dataNascimento: "1994-01-08",
    telefone: "(84) 3344-3003",
    cidade: "Natal",
    email: "fernanda@example.com",
    celular: "(85) 99999-3003",
    logradouro: "Rua do Sol",
    numero: "98",
    complemento: "Casa",
    bairro: "Ponta Negra",
    estado: "RN",
    cep: "59090-000",
    pais: "Brasil",
    status: "vip",
    observacao: "Prefere unidades silenciosas."
  }
];

export const fallbackReservas = fallbackDashboard.recentReservations;

export const fallbackReservasDetalhadas = [
  {
    id: 1001,
    idChale: 1,
    idCliente: 1,
    dataReserva: "2026-04-02",
    dataCheckinPrevisto: "2026-04-05",
    dataCheckoutPrevisto: "2026-04-08",
    dataCheckinReal: "2026-04-05",
    dataCheckoutReal: "",
    qtdAdultos: 2,
    qtdCriancas: 1,
    qtdHospedes: 3,
    qtdNoites: 3,
    valorDiariaAplicada: 650,
    valorTotalHospedagem: 1950,
    valorDesconto: 0,
    valorTaxaLimpeza: 0,
    valorTaxaExtra: 0,
    valorTotalReserva: 1950,
    statusReserva: "confirmada",
    origemReserva: "site",
    observacao: ""
  },
  {
    id: 1002,
    idChale: 3,
    idCliente: 2,
    dataReserva: "2026-04-02",
    dataCheckinPrevisto: "2026-04-06",
    dataCheckoutPrevisto: "2026-04-09",
    dataCheckinReal: "",
    dataCheckoutReal: "",
    qtdAdultos: 2,
    qtdCriancas: 0,
    qtdHospedes: 2,
    qtdNoites: 3,
    valorDiariaAplicada: 480,
    valorTotalHospedagem: 1440,
    valorDesconto: 0,
    valorTaxaLimpeza: 40,
    valorTaxaExtra: 0,
    valorTotalReserva: 1480,
    statusReserva: "pendente",
    origemReserva: "whatsapp",
    observacao: ""
  },
  {
    id: 1003,
    idChale: 2,
    idCliente: 3,
    dataReserva: "2026-04-02",
    dataCheckinPrevisto: "2026-04-07",
    dataCheckoutPrevisto: "2026-04-10",
    dataCheckinReal: "2026-04-07",
    dataCheckoutReal: "",
    qtdAdultos: 4,
    qtdCriancas: 0,
    qtdHospedes: 4,
    qtdNoites: 3,
    valorDiariaAplicada: 720,
    valorTotalHospedagem: 2160,
    valorDesconto: 0,
    valorTaxaLimpeza: 80,
    valorTaxaExtra: 0,
    valorTotalReserva: 2240,
    statusReserva: "hospedado",
    origemReserva: "booking",
    observacao: ""
  }
];
